<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lívia Neves Rodrigues Vitor Estevam">

<title>Análise de Acidentes Rodoviários em Minas Gerais</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="projeto_files/libs/clipboard/clipboard.min.js"></script>
<script src="projeto_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="projeto_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="projeto_files/libs/quarto-html/popper.min.js"></script>
<script src="projeto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="projeto_files/libs/quarto-html/anchor.min.js"></script>
<link href="projeto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="projeto_files/libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="projeto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="projeto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="projeto_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise de Acidentes Rodoviários em Minas Gerais</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lívia Neves Rodrigues Vitor Estevam </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introdução" class="level1">
<h1>1 Introdução</h1>
<p>O presente relatório tem como objetivo realizar uma análise descritiva da base de dados de acidentes rodoviários registrados em Minas Gerais no ano de 2020. A análise busca identificar padrões, distribuições e possíveis associações relacionadas aos acidentes, considerando variáveis temporais, espaciais e características dos registros.</p>
<p>Inicialmente, foi realizada uma etapa de tratamento e organização dos dados, envolvendo verificação de inconsistências, padronização das variáveis e criação de novas variáveis auxiliares para facilitar as análises posteriores. Em seguida, foram desenvolvidas análises exploratórias univariadas e bivariadas, utilizando medidas descritivas, tabelas de frequência e representações gráficas.</p>
<p>Além disso, o projeto busca explorar relações entre fatores como período do dia, tipo de acidente, condições meteorológicas e características das rodovias, visando obter uma compreensão mais detalhada do comportamento dos acidentes registrados no estado.</p>
</section>
<section id="base-de-dados" class="level1">
<h1>2 Base de dados</h1>
<section id="estrutura-da-base" class="level2">
<h2 class="anchored" data-anchor-id="estrutura-da-base">2.1 Estrutura da base</h2>
<p>A base de dados utilizada contém informações dos acidentes ocorridos nas rodovias federais de Minas Gerais no ano de 2020. Após o carregamento de dados, verificou-se a presença de 6536 observações e 21 variáveis, contendo informações dos acidentes, vítimas, características da rodovia e condições ambientais</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                     Variavel    Classe
id                                         id   numeric
data_inversa                     data_inversa   POSIXct
horario                               horario   POSIXct
horario_formatado           horario_formatado character
hora                                     hora   integer
periodo                               periodo   ordered
fase_dia                             fase_dia character
mes                                       mes   ordered
dia_semana                         dia_semana   ordered
uf                                         uf character
br                                         br character
km                                         km   numeric
municipio                           municipio character
tipo_acidente                   tipo_acidente character
condicao_metereologica condicao_metereologica character
tipo_pista                         tipo_pista character
pessoas                               pessoas   numeric
mortos                                 mortos   numeric
feridos_leves                   feridos_leves   numeric
feridos_graves                 feridos_graves   numeric
ilesos                                 ilesos   numeric
feridos                               feridos   numeric
veiculos                             veiculos   numeric
latitude                             latitude   numeric
longitude                           longitude   numeric</code></pre>
</div>
</div>
</section>
<section id="classificação-de-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="classificação-de-variáveis">2.2 Classificação de variáveis</h2>
<p>As varíaveis da base foram separadas de acordo com sua característica estatística.</p>
<p>As variáveis qualitativas descrevem categorias e não podem ser medidas numericamente e geralmente são representadas por porcentagens ou contagens.</p>
<section id="ordinal" class="level3">
<h3 class="anchored" data-anchor-id="ordinal">2.2.1 Ordinal</h3>
<ul>
<li><p>data_inversa</p></li>
<li><p>dia_semana</p></li>
<li><p>fase_dia</p></li>
</ul>
</section>
<section id="nominal" class="level3">
<h3 class="anchored" data-anchor-id="nominal">2.2.2 Nominal</h3>
<ul>
<li><p>município</p></li>
<li><p>tipo_acidente</p></li>
<li><p>condicao_metereologica</p></li>
<li><p>tipo_pista</p></li>
<li><p>uf</p></li>
<li><p>br</p></li>
<li><p>id</p></li>
</ul>
<p>As variáveis quantitativas representam dados que podem ser medidos ou quantificados numericamente.</p>
</section>
<section id="contínuas" class="level3">
<h3 class="anchored" data-anchor-id="contínuas">2.2.1 Contínuas</h3>
<ul>
<li><p>latitude</p></li>
<li><p>longitude</p></li>
<li><p>horario</p></li>
<li><p>km</p></li>
</ul>
</section>
<section id="discretas" class="level3">
<h3 class="anchored" data-anchor-id="discretas">2.2.2 Discretas</h3>
<ul>
<li><p>pessoas</p></li>
<li><p>feridos</p></li>
<li><p>feridos_leves</p></li>
<li><p>feridos_graves</p></li>
<li><p>veiculos</p></li>
<li><p>mortos</p></li>
<li><p>ilesos</p></li>
</ul>
</section>
</section>
</section>
<section id="limpeza-e-tratamento-de-dados" class="level1">
<h1>3 Limpeza e tratamento de dados</h1>
<section id="valores-ausentes" class="level2">
<h2 class="anchored" data-anchor-id="valores-ausentes">3.1 Valores ausentes</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                     Variavel Valores_Ausentes
id                                         id                0
data_inversa                     data_inversa                0
horario                               horario                0
horario_formatado           horario_formatado                0
hora                                     hora                0
periodo                               periodo                0
fase_dia                             fase_dia                0
mes                                       mes                0
dia_semana                         dia_semana                0
uf                                         uf                0
br                                         br                0
km                                         km                4
municipio                           municipio                0
tipo_acidente                   tipo_acidente                0
condicao_metereologica condicao_metereologica                0
tipo_pista                         tipo_pista                0
pessoas                               pessoas                0
mortos                                 mortos                0
feridos_leves                   feridos_leves                0
feridos_graves                 feridos_graves                0
ilesos                                 ilesos                0
feridos                               feridos                0
veiculos                             veiculos                0
latitude                             latitude                0
longitude                           longitude                0</code></pre>
</div>
</div>
<p>Foi realizada a verificação de valores ausentes na base de dados utilizando funções de contagem de NA. Observou-se a presença de poucos valores ausentes na variável km. Após investigação, verificou-se que esses valores já estavam originalmente ausentes na base de dados, não sendo gerados durante o processo de transformação das variáveis.</p>
</section>
<section id="padronização-das-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="padronização-das-variáveis">3.2 Padronização das variáveis</h2>
<p>A variável <code>br</code> foi modificada, removendo-se o sufixo <code>.0</code> e adicionando-se o prefixo <code>BR-</code>, com o objetivo de melhorar a padronização textual.</p>
<p>A variável <code>mes</code> foi elaborada a partir de <code>data_inversa</code>, visando simplificar a criação de gráficos e análises temporais.</p>
<p>A variável <code>horario_formatado</code> foi criada porque a variável original <code>horario</code> continha inconsistências relacionadas ao formato entre data e hora, sendo extraída apenas a informação referente ao horário.</p>
<p>A variável <code>hora</code> originou-se da variável <code>horario</code>, com a finalidade de facilitar a legibilidade dos gráficos e análises, uma vez que a representação em valores inteiros torna a visualização mais simples.</p>
<p>A variável <code>periodo</code> foi derivada da variável <code>hora</code> com o objetivo de consolidar a variável <code>fase_dia</code>, pois esta apresentava categorias muito fragmentadas, o que dificultaria as análises temporais.</p>
</section>
<section id="variáveis-temporais" class="level2">
<h2 class="anchored" data-anchor-id="variáveis-temporais">3.3 Variáveis temporais</h2>
<p>Foram criadas variáveis temporais derivadas das já existentes no banco de dados, com a finalidade de melhorar a legibilidade e facilitar a interpretação dos dados ao longo do tempo.</p>
</section>
<section id="transformação-de-variáveis" class="level2">
<h2 class="anchored" data-anchor-id="transformação-de-variáveis">3.4 Transformação de variáveis</h2>
<p>A variável <code>fase_dia</code> não foi utilizada nas análises exploratórias, pois apresenta informações semelhantes à variável <code>periodo</code>, criada durante a etapa de tratamento dos dados.</p>
<p>A variável <code>periodo</code> foi construída a partir da variável <code>hora</code>, permitindo uma categorização mais padronizada dos horários dos acidentes em madrugada, manhã, tarde e noite.</p>
<p>Dessa forma, optou-se por utilizar apenas a variável <code>periodo</code> nas análises posteriores, evitando redundância nas interpretações.</p>
<p>Algumas variáveis passaram por transformações para adequação às análises estatísticas. Para melhorar a visualização dos gráficos bivariados envolvendo tipo de acidente, foram selecionados apenas os dez tipos de acidentes com maior frequência de ocorrência, reduzindo a poluição visual e facilitando a interpretação dos resultados.</p>
</section>
<section id="verificação-de-consistência" class="level2">
<h2 class="anchored" data-anchor-id="verificação-de-consistência">3.5 Verificação de consistência</h2>
<p>Também foi realizada uma verificação de consistência entre variáveis relacionadas. Observou-se que a variável feridos corresponde corretamente à soma entre feridos leves e feridos graves, indicando coerência interna nos registros da base.</p>
</section>
</section>
<section id="análise-exploratória" class="level1">
<h1>4 Análise exploratória</h1>
<p>A análise exploratória de dados tem como objetivo compreender o comportamento das variáveis, identificar padrões, valores extremos (outliers) e possíveis relações entre os dados.</p>
<p>Nesta etapa, foram realizadas análises univariadas e bivariadas, utilizando medidas estatísticas e gráficos para facilitar a interpretação dos acidentes registrados nas rodovias de Minas Gerais.</p>
<section id="análise-univariada" class="level2">
<h2 class="anchored" data-anchor-id="análise-univariada">4.1 Análise univariada</h2>
<p>A análise univariada busca estudar cada variável individualmente, permitindo observar sua distribuição, frequência e concentração dos valores.</p>
<p>Para as variáveis numéricas, foram utilizadas medidas descritivas, gráficos de barras e boxplots. Já para as variáveis categóricas, foram utilizadas tabelas de frequência e gráficos de barras.</p>
<section id="váriáveis-numéricas" class="level3">
<h3 class="anchored" data-anchor-id="váriáveis-numéricas">4.1.1 Váriáveis numéricas</h3>
<section id="pessoas" class="level4">
<h4 class="anchored" data-anchor-id="pessoas">Pessoas</h4>
<p>A variável pessoas representa a quantidade de indivíduos envolvidos em cada acidente registrado. Para compreender sua distribuição, foram utilizadas medidas descritivas e gráficos de distribuição.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Pessoas</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">2.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">2.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">3.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">14.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">1.45</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">2.09</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se que a maior parte dos acidentes envolve entre uma e três pessoas, indicando concentração dos valores em faixas mais baixas. A mediana igual a 2 demonstra que metade dos acidentes possui até duas pessoas envolvidas, enquanto a outra metade apresenta valores superiores.</p>
<p>Além disso, o boxplot evidencia a presença de diversos valores extremos (outliers), indicando ocorrências menos frequentes com elevado número de pessoas envolvidas.</p>
<p>A proximidade entre média (2,23) e mediana (2) sugere que, apesar da presença de outliers, a distribuição não apresenta assimetria muito acentuada.</p>
</section>
<section id="feridos-levesgraves" class="level4">
<h4 class="anchored" data-anchor-id="feridos-levesgraves">Feridos( leves/graves)</h4>
<p>As variáveis feridos, feridos_leves e feridos_graves indicam a quantidade de pessoas atingidas nos acidentes e a gravidade dos ferimentos.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Feridos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">1.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">2.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">13.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">1.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">1.14</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Feridos Leves</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">0.98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">11.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">0.98</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">0.97</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-6-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Feridos Graves</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">0.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">8.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">0.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">0.37</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-6-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-6-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Em relação à variável feridos, nota-se que a quantidade de pessoas feridas nos acidentes se concentra principalmente entre zero e duas pessoas. A mediana igual a 1 indica que pelo menos metade dos acidentes apresenta até um ferido.</p>
<p>Com base no boxplot, é possível observar a presença de valores extremos (outliers), indicando poucos acidentes com quantidade elevada de feridos.</p>
<p>A variável feridos_leves apresenta concentração em valores baixos, principalmente entre zero e um ferido leve por acidente. Além disso, a proximidade entre média e mediana sugere distribuição relativamente concentrada nos valores centrais.</p>
<p>Já a variável feridos_graves apresenta forte concentração entre zero e um ferido grave, sendo o valor zero o mais frequente. Também é possível observar a presença de diversos valores extremos, indicando acidentes menos frequentes com maior número de feridos graves.</p>
</section>
<section id="mortos" class="level4">
<h4 class="anchored" data-anchor-id="mortos">Mortos</h4>
<p>A variável mortos indica a quantidade de vítimas fatais nos acidentes.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Mortos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">12.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">0.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">0.14</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar essa variável, percebe-se que a grande maioria dos acidentes não resultou em vítimas fatais. Entretanto, o boxplot evidencia a presença de valores extremos (outliers), indicando a ocorrência de acidentes mais graves, embora menos frequentes.</p>
</section>
<section id="ilesos" class="level4">
<h4 class="anchored" data-anchor-id="ilesos">Ilesos</h4>
<p>A variável ilesos representa a quantidade de pessoas envolvidas nos acidentes que não sofreram ferimentos.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Ilesos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">0.89</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">13.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">1.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">1.17</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se que, na maior parte dos acidentes, entre zero e uma pessoa saiu ilesa. Além disso, a proximidade entre média e mediana sugere distribuição relativamente simétrica dos dados.</p>
<p>Ao analisar o boxplot, percebe-se também a presença de diversos valores extremos (outliers), indicando acidentes com maior quantidade de pessoas ilesas.</p>
</section>
<section id="veículos" class="level4">
<h4 class="anchored" data-anchor-id="veículos">Veículos</h4>
<p>A variável veiculos representa a quantidade de veículos envolvidos em cada acidente.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Resumo estatístico de Veiculos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Medida</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">1º Quartil</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mediana</td>
<td style="text-align: right;">1.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Média</td>
<td style="text-align: right;">1.55</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3º Quartil</td>
<td style="text-align: right;">2.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: right;">9.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: right;">0.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: right;">0.53</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao observar os gráficos e os resumos estatísticos da variável, percebe-se que a maior parte dos acidentes envolveu entre um e dois veículos. A mediana igual a 1 indica que, em pelo menos metade dos acidentes registrados, apenas um veículo estava envolvido.</p>
<p>Além disso, o boxplot evidencia a presença de alguns valores extremos, indicando acidentes com quantidade significativamente maior de veículos envolvidos.</p>
</section>
</section>
<section id="variáveis-categóricas" class="level3">
<h3 class="anchored" data-anchor-id="variáveis-categóricas">4.1.2 Variáveis categóricas</h3>
<p>Condição metereológica</p>
<p>A variável condicao_meteorologica representa as condições climáticas no momento em que o acidente ocorreu.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribuição de Condicao Metereologica</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Condicao Metereologica</th>
<th style="text-align: right;">Frequência</th>
<th style="text-align: right;">Porcentagem (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chuva</td>
<td style="text-align: right;">1208</td>
<td style="text-align: right;">18.48</td>
</tr>
<tr class="even">
<td style="text-align: left;">Céu Claro</td>
<td style="text-align: right;">3960</td>
<td style="text-align: right;">60.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ignorado</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nevoeiro/Neblina</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nublado</td>
<td style="text-align: right;">1225</td>
<td style="text-align: right;">18.74</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se que a maior parte dos acidentes aconteceu em situações de céu claro, totalizando 3.960 ocorrências. Em seguida, destacam-se os acidentes ocorridos em condições de céu nublado, com 1.225 registros.</p>
<p>Por outro lado, condições como nevoeiro ou neblina apresentaram baixa frequência de acidentes, sendo as categorias com menor número de ocorrências na base analisada.</p>
<p>Tipo de pista</p>
<p>A variável tipo_pista indica a configuração da rodovia onde ocorreu o acidente.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribuição de Tipo Pista</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo Pista</th>
<th style="text-align: right;">Frequência</th>
<th style="text-align: right;">Porcentagem (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Dupla</td>
<td style="text-align: right;">2990</td>
<td style="text-align: right;">45.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Múltipla</td>
<td style="text-align: right;">211</td>
<td style="text-align: right;">3.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Simples</td>
<td style="text-align: right;">3335</td>
<td style="text-align: right;">51.03</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se predominância de acidentes em pistas simples, correspondendo a aproximadamente 51% das ocorrências registradas. Esse resultado sugere maior concentração de acidentes em rodovias com esse tipo de configuração.<br>
<br>
Já as pistas múltiplas apresentaram menor frequência de acidentes, totalizando apenas 211 ocorrências.</p>
<p>Período</p>
<p>A variável periodo representa o período do dia em que o acidente ocorreu.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">analise_categorica</span>(acidentes,<span class="st">"periodo"</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribuição de Periodo</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Periodo</th>
<th style="text-align: right;">Frequência</th>
<th style="text-align: right;">Porcentagem (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Madrugada</td>
<td style="text-align: right;">572</td>
<td style="text-align: right;">8.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manhã</td>
<td style="text-align: right;">2000</td>
<td style="text-align: right;">30.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tarde</td>
<td style="text-align: right;">2218</td>
<td style="text-align: right;">33.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Noite</td>
<td style="text-align: right;">1746</td>
<td style="text-align: right;">26.71</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">criar_barplot_numerico</span>(acidentes,<span class="st">"periodo"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se que a maior parte dos acidentes aconteceu nos períodos da tarde e da manhã. O período da tarde concentrou 2.218 ocorrências, correspondendo a aproximadamente 33,9% dos acidentes, enquanto o período da manhã apresentou 2.000 registros, representando cerca de 30,6% das ocorrências.<br>
<br>
Em contrapartida, a madrugada apresentou a menor quantidade de acidentes, com apenas 572 ocorrências, correspondendo a aproximadamente 8,75% do total.</p>
<p>Dia da semana</p>
<p>A variável dia_semana representa o dia da semana em que os acidentes ocorreram.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribuição de Dia Semana</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Dia Semana</th>
<th style="text-align: right;">Frequência</th>
<th style="text-align: right;">Porcentagem (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">segunda</td>
<td style="text-align: right;">857</td>
<td style="text-align: right;">13.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">terça</td>
<td style="text-align: right;">794</td>
<td style="text-align: right;">12.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">quarta</td>
<td style="text-align: right;">825</td>
<td style="text-align: right;">12.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">quinta</td>
<td style="text-align: right;">846</td>
<td style="text-align: right;">12.94</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexta</td>
<td style="text-align: right;">1059</td>
<td style="text-align: right;">16.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">sábado</td>
<td style="text-align: right;">1102</td>
<td style="text-align: right;">16.86</td>
</tr>
<tr class="odd">
<td style="text-align: left;">domingo</td>
<td style="text-align: right;">1053</td>
<td style="text-align: right;">16.11</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se maior concentração de acidentes nos finais de semana e na sexta-feira. O sábado apresentou o maior número de ocorrências, com 1.101 acidentes, correspondendo a aproximadamente 16,9% do total. Em seguida, destacam-se a sexta-feira e o domingo, com aproximadamente 16,2% e 16,1% das ocorrências, respectivamente.<br>
<br>
Por outro lado, a terça-feira apresentou a menor frequência de acidentes, com 794 registros, correspondendo a cerca de 12,2% das ocorrências.</p>
<p>Tipo de acidente</p>
<p>A variável tipo_acidente representa a classificação do acidente registrado.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribuição de Tipo Acidente</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Tipo Acidente</th>
<th style="text-align: right;">Frequência</th>
<th style="text-align: right;">Porcentagem (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Atropelamento de Animal</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">1.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">Atropelamento de Pedestre</td>
<td style="text-align: right;">223</td>
<td style="text-align: right;">3.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Capotamento</td>
<td style="text-align: right;">264</td>
<td style="text-align: right;">4.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colisão frontal</td>
<td style="text-align: right;">543</td>
<td style="text-align: right;">8.31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colisão lateral</td>
<td style="text-align: right;">622</td>
<td style="text-align: right;">9.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Colisão transversal</td>
<td style="text-align: right;">597</td>
<td style="text-align: right;">9.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colisão traseira</td>
<td style="text-align: right;">1066</td>
<td style="text-align: right;">16.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Engavetamento</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">1.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Incêndio</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">2.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">Queda de ocupante de veículo</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">4.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saída de leito carroçável</td>
<td style="text-align: right;">1682</td>
<td style="text-align: right;">25.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tombamento</td>
<td style="text-align: right;">869</td>
<td style="text-align: right;">13.30</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se predominância de acidentes do tipo saída de leito carroçável, correspondendo a aproximadamente 25% das ocorrências, com 1.682 registros. Em seguida, destacam-se os acidentes do tipo colisão traseira, com 1.066 ocorrências, representando cerca de 16,3% do total.<br>
<br>
Já os acidentes do tipo engavetamento apresentaram menor frequência, totalizando apenas 83 ocorrências na base analisada.</p>
<p>BR</p>
<p>A variável br representa a rodovia na qual o acidente ocorreu.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Distribuição de Br</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Br</th>
<th style="text-align: right;">Frequência</th>
<th style="text-align: right;">Porcentagem (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BR-116</td>
<td style="text-align: right;">851</td>
<td style="text-align: right;">13.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-146</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">0.81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-153</td>
<td style="text-align: right;">173</td>
<td style="text-align: right;">2.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-251</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">3.08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-262</td>
<td style="text-align: right;">793</td>
<td style="text-align: right;">12.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-265</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-267</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">1.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-352</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-354</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">0.99</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-356</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">0.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-364</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-365</td>
<td style="text-align: right;">483</td>
<td style="text-align: right;">7.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-381</td>
<td style="text-align: right;">1948</td>
<td style="text-align: right;">29.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-40</td>
<td style="text-align: right;">1282</td>
<td style="text-align: right;">19.61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-459</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">1.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">BR-50</td>
<td style="text-align: right;">421</td>
<td style="text-align: right;">6.44</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BR-NA</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.06</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se que a maior parte dos acidentes ocorreu na BR-381, correspondendo a aproximadamene 30% das ocorrências, com 1948 registros. Já a BR-352 apresenta baixa ocorrência de acidentes, houve apenas uma.</p>
<p>Município</p>
<p>A variável município represenda a cidade onde ocorreu o acidente.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para essa variável, foi utilizado um gráfico com os dez municípios com maior número de ocorrências de acidentes. Com base no gráfico, observa-se que o município com maior quantidade de acidentes é Betim, com 388 ocorrências. Em contraste, o município com menor incidência entre os dez apresentados é Teófilo Otoni, com 98 acidentes.</p>
</section>
</section>
<section id="análise-bivariada" class="level2">
<h2 class="anchored" data-anchor-id="análise-bivariada">4.2 Análise bivariada</h2>
<p>A análise bivariada teve como objetivo investigar relações entre duas variáveis, buscando identificar possíveis associações e padrões nos acidentes.</p>
<p>Foram realizados cruzamentos entre variáveis como tipo de acidente, condição meteorológica, tipo de pista e período do dia, utilizando gráficos comparativos para auxiliar na interpretação dos resultados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a relação entre tipo de pista e tipo de acidente, observa-se que nas pistas duplas os acidentes mais frequentes são saída de leito carroçável e colisão traseira. Já a colisão frontal apresenta baixa incidência nesse tipo de pista.</p>
<p>Nas pistas múltiplas, a quantidade total de acidentes é significativamente menor em comparação aos demais tipos de pista. Entretanto, dentre os acidentes registrados, a colisão traseira aparece como a ocorrência mais frequente.</p>
<p>Em relação às pistas simples, nota-se maior concentração de acidentes do tipo saída de leito carroçável. Em seguida, destacam-se colisão frontal, colisão transversal e tombamento, indicando maior variedade e frequência de acidentes nesse tipo de pista. Além disso, colisão lateral e colisão traseira apresentaram menor incidência em comparação às demais categorias.</p>
<p>De forma geral, percebe-se que as pistas simples concentram a maior quantidade de acidentes e apresentam maior diversidade nos tipos de ocorrência registrados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a relação entre condição meteorológica e tipo de acidente, observa-se que a maior parte dos acidentes ocorreu em situações de céu claro. Nessa condição, o acidente mais frequente é saída de leito carroçável, seguido por colisão traseira e tombamento. As demais categorias, como colisão lateral, colisão frontal e colisão transversal, apresentam incidências menores.</p>
<p>Em situações de chuva, destaca-se de forma significativa a ocorrência de saída de leito carroçável, apresentando frequência muito superior às demais categorias de acidentes. Em segundo lugar aparece a colisão frontal, porém com quantidade consideravelmente inferior.</p>
<p>Quando a condição meteorológica é de céu nublado, novamente a saída de leito carroçável representa a principal ocorrência. Em seguida aparecem colisão traseira e tombamento, com frequências próximas entre si. Já as demais categorias apresentam incidências mais baixas.</p>
<p>Por fim, em condições de nevoeiro ou neblina, observa-se quantidade bastante reduzida de acidentes registrados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a relação entre período do dia e quantidade de mortes, observa-se que a mediana é igual a zero em todos os períodos, indicando que a maior parte dos acidentes não apresentou vítimas fatais.</p>
<p>Entretanto, os boxplots evidenciam a presença de valores extremos (outliers) em todos os períodos do dia, demonstrando que existem ocorrências menos frequentes com elevado número de mortes.</p>
<p>O período da madrugada apresentou o maior valor extremo observado, com aproximadamente 12 mortes em um único acidente, indicando maior gravidade em algumas ocorrências registradas nesse horário.</p>
<p>Além disso, o período da noite apresentou maior concentração de outliers em comparação aos demais períodos, com valores entre aproximadamente 7 e 10 mortes. Já os períodos da manhã e da tarde apresentaram distribuições semelhantes, com valores extremos mais baixos, próximos de cinco mortes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a relação entre tipo de pista e quantidade de mortes, observa-se que a mediana é igual a zero para todos os tipos de pista, indicando que a maior parte dos acidentes registrados não apresentou vítimas fatais.</p>
<p>Entretanto, os boxplots evidenciam a presença de valores extremos (outliers), representando acidentes com maior número de mortes. A pista simples foi o tipo de pista que apresentou os maiores valores extremos, além da maior quantidade de outliers, indicando maior ocorrência de acidentes graves nesse tipo de via. O maior valor observado foi de aproximadamente 12 mortes em um único acidente.</p>
<p>Já a pista dupla apresentou menor quantidade de outliers em comparação à pista simples, com valores máximos próximos de duas mortes. A pista múltipla foi a que apresentou menor quantidade de valores extremos, contendo apenas um outlier com valor relativamente baixo, entre uma e duas mortes.</p>
<p>De forma geral, percebe-se que os acidentes em pistas simples tendem a apresentar maior gravidade quando comparados aos demais tipos de pista.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a distribuição de acidentes por BR, observa-se que a BR-381 apresenta, de forma disparada, a maior quantidade de ocorrências registradas no conjunto de dados. Esse resultado indica elevada concentração de acidentes nessa rodovia em comparação às demais.</p>
<p>Em seguida, destaca-se a BR-040 como a segunda rodovia com maior número de acidentes. Já as BRs 116 e 262 apresentam quantidades semelhantes de ocorrências, com valores próximos entre si.</p>
<p>De forma geral, percebe-se que a BR-381 concentra significativamente mais acidentes do que as outras rodovias analisadas, evidenciando sua relevância dentro do cenário de acidentes nas rodovias de Minas Gerais.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise bivariada entre <code>periodo</code> e <code>tipo_acidente</code> permite observar como os diferentes tipos de acidentes se distribuem ao longo dos períodos do dia. De forma geral, percebe-se que o tipo de acidente mais frequente em todos os períodos é a saída de leito carroçável, indicando que esse padrão se mantém independentemente do horário analisado.</p>
<p>Durante a madrugada, observa-se uma concentração mais acentuada de acidentes por saída de leito carroçável, representando mais de 25% dos acidentes registrados nesse período. Em seguida, destaca-se a colisão traseira. Já os acidentes menos frequentes durante a madrugada correspondem aos atropelamentos de animais.</p>
<p>No período da manhã, novamente predominam os acidentes por saída de leito carroçável, seguidos pelas colisões traseiras e pelos tombamentos. Esse comportamento indica certa continuidade do padrão observado na madrugada, embora com distribuição um pouco menos concentrada.</p>
<p>Durante a tarde, a saída de leito carroçável continua sendo o tipo de acidente mais incidente, seguida pelas colisões traseiras e colisões transversais. As demais categorias, como capotamento, colisão lateral e tombamento, apresentam frequências relativamente semelhantes, enquanto o atropelamento de animais permanece entre os menos frequentes.</p>
<p>No período da noite, observa-se uma distribuição mais equilibrada entre os tipos de acidentes. A saída de leito carroçável ainda aparece como a principal ocorrência, porém praticamente empatada com as colisões traseiras, indicando uma menor concentração em um único tipo de acidente quando comparado aos demais períodos do dia.</p>
</section>
<section id="análise-temporal" class="level2">
<h2 class="anchored" data-anchor-id="análise-temporal">4.3 Análise temporal</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a distribuição temporal dos acidentes ao longo dos meses do ano, observa-se que o mês de dezembro apresenta a maior quantidade de ocorrências registradas, indicando um pico significativo no número de acidentes nesse período. Em seguida, destaca-se o mês de outubro como o segundo com maior incidência de acidentes. Os meses de setembro e janeiro também apresentam valores elevados e bastante próximos entre si.</p>
<p>Por outro lado, o mês de abril apresenta a menor quantidade de acidentes registrados, representando o ponto de menor incidência ao longo do ano.</p>
<p>Observando o comportamento temporal da série, percebe-se uma redução gradual no número de acidentes entre janeiro e abril, período em que é atingido o menor valor observado. A partir de maio ocorre uma elevação significativa nas ocorrências, seguida por certa estabilidade entre maio e junho.</p>
<p>Entre julho e agosto observa-se um novo aumento mais acentuado na quantidade de acidentes, enquanto entre agosto, setembro e outubro o crescimento continua de forma mais moderada. Já entre outubro e novembro ocorre uma queda significativa nas ocorrências, seguida por um novo aumento expressivo em dezembro, mês que concentra o maior número de acidentes registrados.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ao analisar a distribuição de acidentes por dia da semana, observa-se que o sábado apresenta a maior quantidade de ocorrências registradas, sendo o dia com maior incidência de acidentes. Em seguida, destacam-se a sexta-feira e o domingo, que apresentam valores bastante próximos, embora a sexta-feira possua quantidade ligeiramente superior.</p>
<p>Dessa forma, percebe-se que os acidentes se concentram principalmente no período correspondente ao final de semana, especialmente entre sexta-feira, sábado e domingo.</p>
<p>Já nos demais dias da semana, segunda-feira, quinta-feira, quarta-feira e terça-feira apresentam quantidades relativamente semelhantes de acidentes, com menor variação entre si. Entre esses dias, a terça-feira corresponde ao menor número de ocorrências registradas.</p>
<p>De maneira geral, a ordem dos dias com maior incidência de acidentes, do mais frequente para o menos frequente, é: sábado, sexta-feira, domingo, segunda-feira, quinta-feira, quarta-feira e terça-feira.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projeto_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A maior incidência de acidentes ocorre no período da tarde, seguido pelo período da manhã. Em seguida, observa-se uma redução no período da noite, enquanto a madrugada apresenta a menor quantidade de registros.</p>
<p>Nota-se uma diferença bastante expressiva entre a tarde e a madrugada, evidenciando uma concentração de acidentes no período vespertino. A diferença entre tarde e manhã, embora existente, é menos acentuada. Já entre manhã e noite, a variação é moderada e semelhante à observada entre noite e madrugada. Em síntese, o período da tarde se destaca como o de maior ocorrência de acidentes, enquanto a madrugada apresenta os menores índices.</p>
</section>
<section id="análise-espacial" class="level2">
<h2 class="anchored" data-anchor-id="análise-espacial">4.4 Análise espacial</h2>
</section>
</section>
<section id="conclusão" class="level1">
<h1>5 Conclusão</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>